name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # 触发分支，根据你的主分支名称修改

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入仓库

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 重要！如果使用子模块主题需要此参数

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm # or pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: |
          npm run docs:build # or pnpm docs:build / yarn docs:build / bun run docs:build
          touch .vitepress/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist   # Hugo 默认输出目录
          # 如果使用 docs 目录部署，请改为：
          # publish_dir: ./docs